#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/proxy
- name: Stop whatever tf is running on :80
  community.docker.docker_container:
    name: httpd
    image: nginx
    ports: 
      - "80:80"

- name: Launch the reverse proxy
  community.docker.docker_container:
    name: httpd
    image: "frangipanne/tp-devops-httpd:latest"
    state: started
    restart_policy: always
    
    networks:
      - name: app_network
    
    published_ports:
      - 80:80
  
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3